// Generated by https://quicktype.io

export interface MessageInterface {
    ok:       boolean;
    messages: Message[];
}

export interface Message {
    _id:       string;
    de:        string;
    para:      string;
    mensaje:   string;
    createdAt: string;
    updatedAt: string;
}
